vich_uploader:
    db_driver: orm

    mappings:
        medias:
            uri_prefix: /medias
            upload_destination: '%kernel.project_dir%/public/medias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true